const sampleData = {
  products: [
    {
      slug: "century-eggs-with-chili-dressing",
      name: "Century Eggs With Chili Dressing",
      nameChinese: "剁椒皮蛋",
      category: "Starters",
      description:
        "Silky preserved duck eggs topped with a savory and spicy chopped chili dressing.",
      image: "/image/food/Starters/Century Eggs with Chili Dressing.jpg",
      price: 6.66,
      isFeatured: false,
      outOfStock: true,
    },
    {
      slug: "mouth-watering-chicken",
      name: "Mouth-Watering Chicken",
      nameChinese: "口水鸡",
      category: "Starters",
      description:
        "Tender poached chicken drenched in a signature Sichuan chili oil sauce with peanuts and sesame.",
      image: "/image/food/Starters/Mouth-watering Chicken.png",
      price: 9.99,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "pickled-chicken-feet-with-wild-chili",
      name: "Pickled Chicken Feet With Wild Chili",
      nameChinese: "泡椒凤爪",
      category: "Starters",
      description:
        "Crunchy chicken feet pickled with spicy wild peppers for a refreshing, tangy kick.",
      image: "/image/food/Starters/Pickled Chicken Feet with Wild Chili.jpg",
      price: 7.77,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "sichuan-cold-spicy-rabbit",
      name: "Sichuan Cold Spicy Rabbit",
      nameChinese: "自贡冷吃兔",
      category: "Starters",
      description:
        "Authentic Zigong-style diced rabbit meat, chewy and infused with aromatic spices and chilies.",
      image: "/image/food/Starters/Sichuan Cold Spicy Rabbit.jpg",
      price: 11.88,
      isFeatured: false,
      outOfStock: true,
    },
    {
      slug: "sliced-pork-with-garlic-sauce",
      name: "Sliced Pork With Garlic Sauce",
      nameChinese: "蒜泥白肉",
      category: "Starters",
      description:
        "Thinly sliced pork belly served with a rich, aromatic garlic soy sauce and chili oil.",
      image: "/image/food/Starters/Sliced Pork with Garlic Sauce.png",
      price: 11.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "steamed-egg-custard",
      name: "Steamed Egg Custard",
      nameChinese: "滋润蒸蛋羹",
      category: "Starters",
      description:
        "Silky smooth, melt-in-your-mouth steamed eggs seasoned with a hint of light soy sauce.",
      image: "/image/food/Starters/Steamed Egg Custard.jpg",
      price: 7.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "apple-green-tea",
      name: "Apple Green Tea",
      nameChinese: "苹果绿茶",
      category: "Drinks",
      description:
        "A refreshing blend of premium green tea and the crisp, sweet flavor of fresh apples.",
      image: "/image/food/Drinks/Apple Green Tea.jpg",
      price: 7.77,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "buttercream-phoenix-dancong-oolong",
      name: "Buttercream Phoenix Dancong Oolong",
      nameChinese: "白脱奶油鸭屎香",
      category: "Drinks",
      description:
        "Floral Phoenix Dancong Oolong tea topped with a rich, velvety layer of buttercream foam.",
      image: "/image/food/Drinks/Buttercream Phoenix Dancong Oolong.jpg",
      price: 7.77,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "hojicha-brown-sugar-latte",
      name: "Hojicha Brown Sugar Latte",
      nameChinese: "焙茶黑糖奶",
      category: "Drinks",
      description:
        "Roasted Japanese green tea paired with caramelized brown sugar and creamy milk.",
      image: "/image/food/Drinks/Hojicha Brown Sugar Latte.jpg",
      price: 7.77,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "hojicha-frappe",
      name: "Hojicha Frappé",
      nameChinese: "焙茶茶冰乐",
      category: "Drinks",
      description:
        "A chilled, blended treat featuring the deep, nutty aroma of roasted hojicha tea.",
      image: "/image/food/Drinks/Hojicha Frappé.jpg",
      price: 7.77,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "matcha-frappe",
      name: "Matcha Frappé",
      nameChinese: "抹茶茶冰乐",
      category: "Drinks",
      description:
        "A classic icy blend of premium Japanese matcha and creamy milk, topped with a hint of sweetness.",
      image: "/image/food/Drinks/Matcha Frappé.jpg",
      price: 7.77,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "molten-chocolate-cocoa",
      name: "Molten Chocolate Cocoa",
      nameChinese: "熔岩可可",
      category: "Drinks",
      description:
        "Indulgent, rich dark chocolate cocoa with a velvety smooth texture.",
      image: "/image/food/Drinks/Molten Chocolate Cocoa.jpg",
      price: 7.77,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "waxberry-tea-frappe",
      name: "Waxberry Tea Frappé",
      nameChinese: "杨梅茶冰乐",
      category: "Drinks",
      description:
        "Sweet and tangy waxberry blended with premium tea and ice for a summer refresher.",
      image: "/image/food/Drinks/Waxberry Tea Frappé.jpg",
      price: 7.77,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "yuzu-lime-tea",
      name: "Yuzu Lime Tea",
      nameChinese: "柚子青柠茶",
      category: "Drinks",
      description:
        "A zesty and invigorating tea combining citrusy yuzu and fresh lime slices.",
      image: "/image/food/Drinks/Yuzu Lime Tea.jpg",
      price: 7.77,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "yuzu-matcha-frappe",
      name: "Yuzu Matcha Frappé",
      nameChinese: "柚子抹茶冰",
      category: "Drinks",
      description:
        "A unique fusion of earthy matcha and bright, citrusy yuzu in a blended icy format.",
      image: "/image/food/Drinks/Yuzu Matcha Frappé.jpg",
      price: 7.77,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "bingfen-with-snow-fungus",
      name: "Bingfen With Snow Fungus",
      nameChinese: "银耳冰粉",
      category: "Desserts",
      description:
        "Traditional Sichuan ice jelly served with nutritious snow fungus and sweet syrup.",
      image: "/image/food/Desserts/Bingfen with Snow Fungus.jpg",
      price: 8.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "brown-sugar-sticky-rice-cake",
      name: "Brown Sugar Sticky Rice Cake",
      nameChinese: "红糖糍粑",
      category: "Desserts",
      description:
        "Crispy fried glutinous rice cakes drizzled with rich brown sugar syrup and soybean powder.",
      image: "/image/food/Desserts/Brown Sugar Sticky Rice Cake.jpg",
      price: 8.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "sweet-fermented-rice-soup-with-tangyuan",
      name: "Sweet Fermented Rice Soup With Tangyuan",
      nameChinese: "酒酿圆子",
      category: "Desserts",
      description:
        "A warm, comforting dessert soup made with fermented rice and chewy mini glutinous balls.",
      image: "/image/food/Desserts/Sweet Fermented Rice Soup with Tangyuan.jpg",
      price: 8.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "sweet-osmanthus-cake",
      name: "Sweet Osmanthus Cake",
      nameChinese: "桂花糕",
      category: "Desserts",
      description:
        "Delicate and fragrant steamed rice cakes infused with the floral scent of osmanthus.",
      image: "/image/food/Desserts/Sweet Osmanthus Cake.jpg",
      price: 8.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "dry-fried-cabbage",
      name: "Dry-Fried Cabbage",
      nameChinese: "手撕包菜",
      category: "Greens",
      description:
        "Wok-seared cabbage with garlic, dried chilies, and a hint of vinegar for a smoky crunch.",
      image: "/image/food/Greens/Dry-fried Cabbage.jpg",
      price: 9.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "dry-fried-green-beans",
      name: "Dry-Fried Green Beans",
      nameChinese: "干煸四季豆",
      category: "Greens",
      description:
        "Classic Sichuan-style green beans stir-fried with minced pork, garlic, and preserved vegetables.",
      image: "/image/food/Greens/Dry-fried Green Beans.jpg",
      price: 9.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "stir-fried-choy-sum",
      name: "Stir-Fried Choy Sum",
      nameChinese: "清炒菜心",
      category: "Greens",
      description:
        "Fresh and crunchy Choy Sum quickly stir-fried with garlic to preserve its natural sweetness.",
      image: "/image/food/Greens/Stir-fried Choy Sum.jpg",
      price: 9.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "stir-fried-eggplant-and-string-beans",
      name: "Stir-Fried Eggplant And String Beans",
      nameChinese: "茄子炒豆角",
      category: "Greens",
      description:
        "A savory and popular combination of tender eggplant and snappy string beans in a garlic sauce.",
      image: "/image/food/Greens/Stir-fried Eggplant and String Beans.jpg",
      price: 9.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "stir-fried-indian-lettuce-with-black-bean-sauce",
      name: "Stir-Fried Indian Lettuce With Black Bean Sauce",
      nameChinese: "豆豉油麦菜",
      category: "Greens",
      description:
        "Crisp Indian lettuce stir-fried with savory fermented black beans for an umami-rich flavor.",
      image:
        "/image/food/Greens/Stir-fried Indian Lettuce with Black Bean Sauce.jpg",
      price: 9.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "stir-fried-loofah",
      name: "Stir-Fried Loofah",
      nameChinese: "清炒丝瓜",
      category: "Greens",
      description:
        "Soft and naturally sweet loofah stir-fried until tender, a light and healthy choice.",
      image: "/image/food/Greens/Stir-fried Loofah.jpg",
      price: 9.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "stir-fried-pea-shoots",
      name: "Stir-Fried Pea Shoots",
      nameChinese: "清炒豆苗",
      category: "Greens",
      description:
        "Delicate and tender pea shoots quickly sautéed with garlic for a fresh, vibrant taste.",
      image: "/image/food/Greens/Stir-fried Pea Shoots.jpg",
      price: 9.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "stir-fried-water-spinach",
      name: "Stir-Fried Water Spinach",
      nameChinese: "蒜蓉空心菜",
      category: "Greens",
      description:
        "Fresh water spinach wok-fried with plenty of garlic, a staple of Asian home cooking.",
      image: "/image/food/Greens/Stir-fried Water Spinach.jpg",
      price: 9.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "braised-soft-shell-turtle-in-brown-sauce",
      name: "Braised Soft-Shell Turtle In Brown Sauce",
      nameChinese: "黄焖大甲鱼",
      category: "Mains",
      description:
        "A highly nutritious delicacy slow-braised in a rich, savory brown sauce until tender.",
      image: "/image/food/Mains/Braised Soft-shell Turtle in Brown Sauce.jpg",
      price: 16.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "bullfrog-with-fresh-chili",
      name: "Bullfrog With Fresh Chili",
      nameChinese: "鲜椒霸王蛙",
      category: "Mains",
      description:
        "Succulent bullfrog pieces cooked in a fiery pot with fresh green and red chilies.",
      image: "/image/food/Mains/Bullfrog with Fresh Chili.png",
      price: 15.66,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "dry-fried-shrimp",
      name: "Dry-Fried Shrimp",
      nameChinese: "干煸大虾",
      category: "Mains",
      description:
        "Crispy, wok-fried jumbo prawns seasoned with Sichuan peppercorns and aromatic spices.",
      image: "/image/food/Mains/Dry-fried Shrimp.jpg",
      price: 12.99,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "oil-boiling-fish",
      name: "Oil Boiling Fish",
      nameChinese: "油泼沸腾鱼",
      category: "Mains",
      description:
        "Fresh fish fillets submerged in a fragrant, bubbling pool of spicy chili oil and peppercorns.",
      image: "/image/food/Mains/Oil Boiling Fish.jpg",
      price: 12.99,
      isFeatured: true,
      outOfStock: false,
    },
    {
      slug: "pork-meatballs-in-brown-sauce",
      name: "Pork Meatballs In Brown Sauce",
      nameChinese: "红烧狮子头",
      category: "Mains",
      description:
        "Giant, succulent pork meatballs braised in a savory dark sauce, also known as Lion's Head.",
      image: "/image/food/Mains/Pork Meatballs in Brown Sauce.jpg",
      price: 12.99,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "sauerkraut-fish",
      name: "Sauerkraut Fish",
      nameChinese: "老坛酸菜鱼",
      category: "Mains",
      description:
        "Silky fish fillets poached in a tangy and mildly spicy broth with authentic Sichuan pickled greens.",
      image: "/image/food/Mains/Sauerkraut Fish.png",
      price: 12.99,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "sichuan-boiled-beef",
      name: "Sichuan Boiled Beef",
      nameChinese: "水煮牛肉",
      category: "Mains",
      description:
        "Tender beef slices poached in a bold, numbing Sichuan chili broth and finished with hot oil.",
      image: "/image/food/Mains/Sichuan Boilded Beef.png",
      price: 14.88,
      isFeatured: true,
      outOfStock: false,
    },
    {
      slug: "sichuan-boiled-fish",
      name: "Sichuan Boiled Fish",
      nameChinese: "水煮鱼",
      category: "Mains",
      description:
        "Delicate fish fillets simmered in a classic fiery Sichuan peppercorn and chili broth.",
      image: "/image/food/Mains/Sichuan Boiled Fish.png",
      price: 12.99,
      isFeatured: true,
      outOfStock: false,
    },
    {
      slug: "snow-beef-mapo-tofu",
      name: "Snow Beef Mapo Tofu",
      nameChinese: "雪花牛肉麻婆豆腐",
      category: "Mains",
      description:
        "A premium version of Mapo Tofu featuring marbled beef and silky tofu in a spicy bean sauce.",
      image: "/image/food/Mains/Snow Beef Mapo Tofu.jpg",
      price: 12.99,
      isFeatured: true,
      outOfStock: false,
    },
    {
      slug: "spicy-rabbit-in-hot-pot",
      name: "Spicy Rabbit In Hot Pot",
      nameChinese: "自贡鲜锅兔",
      category: "Mains",
      description:
        "Diced rabbit stir-fried with aromatic spices, lotus root, and chilies, served in a sizzling dry pot.",
      image: "/image/food/Mains/Spicy Rabbit in Hot Pot.png",
      price: 12.99,
      isFeatured: true,
      outOfStock: true,
    },
    {
      slug: "spicy-stew-with-beef-tripe-and-blood-curd",
      name: "Spicy Stew With Beef Tripe And Blood Curd",
      nameChinese: "山城毛血旺",
      category: "Mains",
      description:
        "A classic Sichuan stew with beef tripe, duck blood curd, and various ingredients in a spicy broth.",
      image: "/image/food/Mains/Spicy Stew with Beef Tripe and Blood Curd.png",
      price: 11.66,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "steamed-prawns-with-garlic-and-vermicelli",
      name: "Steamed Prawns With Garlic And Vermicelli",
      nameChinese: "蒜蓉粉丝蒸大虾",
      category: "Mains",
      description:
        "Butterflied jumbo prawns steamed with a rich garlic paste on a bed of silky vermicelli.",
      image: "/image/food/Mains/Steamed Prawns with Garlic and Vermicelli.jpg",
      price: 12.99,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "stir-fried-beef-with-black-pepper",
      name: "Stir-Fried Beef With Black Pepper",
      nameChinese: "黑椒牛柳",
      category: "Mains",
      description:
        "Tender strips of beef stir-fried with a bold black pepper sauce, onions, and bell peppers.",
      image: "/image/food/Mains/Stir-fried Beef with Black Pepper.png",
      price: 12.99,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "stir-fried-pork-kidney-and-liver",
      name: "Stir-Fried Pork Kidney And Liver",
      nameChinese: "爆炒腰肝",
      category: "Mains",
      description:
        "A high-heat stir-fry of tender pork kidney and liver with ginger, garlic, and scallions.",
      image: "/image/food/Mains/Stir-fried Pork Kidney and Liver.png",
      price: 12.99,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "sweet-and-sour-pork-with-pineapple",
      name: "Sweet And Sour Pork With Pineapple",
      nameChinese: "菠萝咕噜肉",
      category: "Mains",
      description:
        "Crispy pork nuggets tossed in a vibrant sweet and sour sauce with fresh pineapple and peppers.",
      image: "/image/food/Mains/Sweet and Sour Pork with Pineapple.png",
      price: 12.99,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "chengdu-dan-dan-noodles",
      name: "Chengdu Dan Dan Noodles",
      nameChinese: "成都担担面",
      category: "Staples",
      description:
        "Famous Sichuan noodles topped with a savory minced pork sauce, peanuts, and chili oil.",
      image: "/image/food/Staples/Chengdu Dan Dan Noodles.jpg",
      price: 8.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "clear-jelly-noodles-in-chili-sauce",
      name: "Clear Jelly Noodles In Chili Sauce",
      nameChinese: "川北凉粉",
      category: "Staples",
      description:
        "Cool mung bean jelly noodles tossed in a bold, spicy, and tangy Sichuan dressing.",
      image: "/image/food/Staples/Clear Jelly Noodles in Chili Sauce.jpg",
      price: 8.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "cold-noodles-with-shredded-chicken",
      name: "Cold Noodles With Shredded Chicken",
      nameChinese: "鸡丝凉面",
      category: "Staples",
      description:
        "Chilled noodles topped with tender shredded chicken and a nutty, spicy sesame dressing.",
      image: "/image/food/Staples/Cold Noodles with Shredded Chicken.jpg",
      price: 11.88,
      isFeatured: true,
      outOfStock: false,
    },
    {
      slug: "fried-rice",
      name: "Fried Rice",
      nameChinese: "经典炒饭",
      category: "Staples",
      description:
        "Fragrant jasmine rice wok-fried with eggs, scallions, and choice of seasonal vegetables.",
      image: "/image/food/Staples/Fried Rice.jpg",
      price: 8.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "pork-wonton-in-hot-oil",
      name: "Pork Wonton In Hot Oil",
      nameChinese: "红油抄手",
      category: "Staples",
      image: "/image/food/Staples/Wonton in Hot Oil.jpg",
      price: 8.88,
      isFeatured: false,
      outOfStock: false,
    },
    {
      slug: "shrimp-wonton-in-hot-oil",
      name: "Shrimp Wonton In Hot Oil",
      nameChinese: "鲜虾红油抄手",
      category: "Staples",
      price: 9.88,
      isFeatured: false,
      outOfStock: false,
    },
  ],
};

export default sampleData;
